name: Deploy App
on: [push]

jobs:
  test-and-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Use node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache Node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: install deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install --silent

      - name: lint
        run: npm run lint

      - name: e2e
        run: npm run e2e -- --headless

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: client-e2e
          path: ./dist/cypress/client/**

      - name: build
        run: npm run build -c=production

      - uses: actions/upload-artifact@v1
        with:
          name: client-build-files
          path: ./dist/client

  deploy:
    runs-on: ubuntu-20.04
    # taken from https://github.community/t/trigger-job-on-tag-push-only/18076
    if: contains(github.ref, 'refs/tags/')
    needs: test-and-build
    steps:
      - name: get build files
        uses: actions/download-artifact@master
        with:
          name: client-build-files
          path: ./dist/client

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./dist/client
