name: test on commit
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  test-on-commit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Use node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install deps
        run: npm ci

      - name: lint
        run: npm run lint

      - name: e2e
        run: npm run e2e -- --headless

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: client-e2e
          path: ./dist/cypress/client/**

      - name: build
        run: npm run build -c=production
